services:
  api:
    container_name: souvenir-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: souvenir-db
    image: postgres:16.3
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    container_name: souvenir-adminer
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    container_name: souvenir-mailpit
    volumes:
      - mailpit-data:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH: ${MP_SMTP_AUTH}
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db-data:
  mailpit-data:
